POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "oh",
    "important": true

}
###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "Test if still works",
    "important": true

}
